image: node:18.19-alpine # Specify the Docker image to be used for all jobs

stages:
  - install_dependencies
  - install_angular
  - build

# Job to install npm dependencies
install_dep:
  stage: install_dependencies
  image: node:18
  script:
    - npm install

# Job to install Angular CLI and TypeScript
install_ang:
  stage: install_angular
  image: node:18
  script:
    - npm install -D typescript @angular/cli @angular/compiler

# Job to build the Angular application
build_ang:
  stage: build
  image: node:18 # Using Node 18 image
  script:
    - npm run build
